/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package edu.weber.cs3230.projects.finalproject;

import javax.swing.*;
import java.math.BigDecimal;

/**
 *
 * @author zycmm
 */
public class WithdrawDialog extends JDialog {

    /**
     * Creates new form DepositDialog
     */
    public WithdrawDialog(java.awt.Frame parent, boolean modal, BankAccount account) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        withdrawAmountLabel = new JLabel();
        withdrawAmountTextField = new JTextField();
        withdrawOKButton = new JButton();
        withdrawCancelButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        withdrawAmountLabel.setText("Withdraw Amount:");
        getContentPane().add(withdrawAmountLabel);
        getContentPane().add(withdrawAmountTextField);

        withdrawOKButton.setText("OK");
        withdrawOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawOKButtonActionPerformed(evt);
            }
        });
        getContentPane().add(withdrawOKButton);

        withdrawCancelButton.setText("Cancel");
        withdrawCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawCancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(withdrawCancelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_withdrawCancelButtonActionPerformed

// WithdrawDialog.java

    // Method to handle OK button action in Withdraw Dialog
    public void withdrawOKButtonActionPerformed(java.awt.event.ActionEvent evt) {
        StringBuilder warnings = new StringBuilder();
        String amountStr = amountTextField.getText();

        if (amountStr.isEmpty()) {
            warnings.append("Withdrawal amount is empty.\n");
        } else {
            try {
                BigDecimal amount = new BigDecimal(amountStr);
                if (amount.compareTo(BigDecimal.ZERO) > 0) {
                    selectedAccount.withdraw(amount);
                } else {
                    warnings.append("Amount must be greater than zero.\n");
                }
            } catch (InsufficientFundException ife) {
                warnings.append(ife.getMessage());
            } catch (NumberFormatException nfe) {
                warnings.append("Invalid amount format.\n");
            }
        }

        if (warnings.length() > 0) {
            JOptionPane.showMessageDialog(this, warnings.toString(), "Withdrawal Warning", JOptionPane.WARNING_MESSAGE);
        }

        dispose();
    }


    public JLabel getWithdrawAmountLabel() {
        return withdrawAmountLabel;
    }

    public JTextField getWithdrawAmountTextField() {
        return withdrawAmountTextField;
    }

    public JButton getWithdrawCancelButton() {
        return withdrawCancelButton;
    }

    public JButton getWithdrawOKButton() {
        return withdrawOKButton;
    }

    public BankAccount getAccount() {
        return account;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel withdrawAmountLabel;
    private JTextField withdrawAmountTextField;
    private JButton withdrawCancelButton;
    private JButton withdrawOKButton;
    // End of variables declaration//GEN-END:variables
    
    private BankAccount account;

}
